# Site settings
title: Tristan Mendoza
email: tristanm.tx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Right now this is simply a placeholder.  I hope to put up some 
  final versions of my quick notes and cheat sheets for networking and 
  sysadmin stuff soon.  Right now, I am a bit too busy to post anything.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tristanmtx.github.io/" # the base hostname & protocol for your site
twitter_username: NO_TWITTER!
github_username:  tristanmtx

# Build settings
markdown: kramdown
