'<span class="yellowsans">Firewall</span>'
'<a class="whitelink" href="http://www.netfilter.org">netfilter.org --iptables --ipset</A>'
'<a class="whitelink" href="http://www.cisco.com/c/en/us/support/security/adaptive-security-appliance-asa-software/tsd-products-support-series-home.html">Cisco ASA Support main</A>'
'<a class="whitelink" href="http://www.cisco.com/c/en/us/support/security/asa-5500-series-next-generation-firewalls/products-command-reference-list.html">Cisco ASA Command Refs</A>'
'<a class="whitelink" href="http://www.cisco.com/c/en/us/support/security/asa-5500-series-next-generation-firewalls/products-installation-and-configuration-guides-list.html">ASA/ASDM Configuration Guides</A>'
'<a class="whitelink" href="https://live.paloaltonetworks.com/">Palo Alto Networks Live</A>'
'<a class="whitelink" href="https://docs.fortinet.com">Fortinet docs and cookbook</A>'
'<a class="whitelink" href="https://community.fireeye.com/">FireEye Community/ Kbase</A>'
'<a class="whitelink" href="https://www.pfsense.org">pfSense Main</A>'
'<a class="whitelink" href="https://forum.pfsense.org/">pfSense Forum</A>'
'<a class="whitelink" href="http://pfsensesetup.com/">pfSense Setup HQ</A>'
'<span class="yellowsans">Misc HW Vendors</span>'
'<a class="whitelink" href="https://www.juniper.net/customers/support/">Juniper Support</A>'
'<a class="whitelink" href="https://support.ruckuswireless.com/">Ruckus Support</A>'
'<a class="whitelink" href="https://market.alcatel-lucent.com/release/jsp/sso/login.jsp">Nokia Alcatel-Lucent Portal</A>' 
'<a class="whitelink" href="https://www.arista.com/en/support/product-documentation">Arista reference docs</A>' 
'<a class="whitelink" href="https://www.arista.com/en/um-eos/eos-command-line-interface">Arista EOS CLI Reference</A>'
'<a class="whitelink" href="https://www.extremenetworks.com/support/">Extreme Networks docs</A>'
'<a class="whitelink" href="https://supportforums.adtran.com">ADTRAN support</A>'
'<a class="whitelink" href="https://www.advaoptical.com">ADVA Optical</A>'
'<a class="whitelink" href="https://www.rad.com/">RAD Optical</A>'
'<a class="whitelink" href="https://www.infoblox.com/">Infoblox</A>'
'<a class="whitelink" href="https://www.riverbed.com">Riverbed</A>' 
'<a class="whitelink" href="https://support.f5.com/">f5 KBase</A>'
'<span class="yellowsans">Tools (mostly in NetOps/NetRecon menus)</span>'
'<a class="whitelink" href="sourceforge.net/projects/ethperf">EthPerf - Y.1731/Y.1564 testing</A>'
'<a class="whitelink" href="github.com/jwbensley/Etherate">Etherrate - Layer 2 testing</A>'
'<a class="whitelink" href="https://iperf.fr/">iPerf3 - L3/4 testing/tuning</A>'
'<a class="whitelink" href="https://sourceforge.net/projects/iperf/files/jperf/jperf%202.0.0/">jPerf (iPerf frontend)</A>'
'<a class="whitelink" href="https://kiminewt.github.io/pyshark/">PyShark - wrapper for TShark</A>' 
'<a class="whitelink" href="https://cloudshark.io/">CloudShark</A>'
'<a class="whitelink" href="https://scapy.net/">Scapy - packet crafting</A>'
'<a class="whitelink" href="https://ostinato.org/">Ostinato - packet gen</a>'
'<a class="whitelink" href="https://osquery.io/">Osquery - query endpoints</A>'
'<a class="whitelink" href="https://osquery.io/schema/3.3.2">Osquery Schema Reference</A>'
'<a class="whitelink" href="https://github.com/maclennann/dashiell">Dashiell - osquery/facter frontend</A>'
'<a class="whitelink" href="https://www.oetiker.ch/en/oss/projects/">Oetiker (SmokePing MRTG RDDTool)</A>'
'<a class="whitelink" href="http://www.slac.stanford.edu/xorg/nmtf/nmtf-tools.html">Net Monitoring Tools list @ Stanford</A>'
'<a class="whitelink" href="https://wiki.wireshark.org/Tools">Wireshark wiki tool list</a>'
'<a class="whitelink" href="http://www.firewall.cx/downloads.html">firewall.cx downloads</A>'
'<span class="yellowsans">Calcs and Practice</span>'
'<a class="whitelink" href="http://rednectar.net/GNS3-workbench/">GNS3 Workbench</A>'
'<a class="whitelink" href="https://gns3vault.com/">GNS3Vault</A>'
'<a class="whitelink" href="http://www.freeccnaworkbook.com/">FreeCCNAWorkbook.com</A>'
'<a class="whitelink" href="http://www.subnettingquestions.com/">SubnettingQuestions.com</A>'
'<a class="whitelink" href="http://www.subnet-calculator.com/">Subnet-calculator.com</A>'
