'<span class="yellowsans">General Reference</span>'
'<a class="whitelink" href="https://www.rfc-editor.org/search/rfc_search.php">RFC Editor search</A>'
'<a class="whitelink" href="https://datatracker.ietf.org/">IETF DataTracker</A>'
'<a class="whitelink" href="https://wiki.wireshark.org/FrontPage">The Wireshark Wiki</A>'
'<a class="whitelink" href="http://www.tcpipguide.com/">TCPIPGuide.com Wiki</A>'
'<a class="whitelink" href="https://wiki.mef.net">MEF (Metro Ethernet Forum) Wiki</A>'
'<a class="whitelink" href="https://wiki.geant.org/display/public/EK/Welcome+to+the+eduPERT+Knowledge+Base">Geant PERT KB</A>
'<a class="whitelink" href="http://www.subnet-calculator.com/">Subnet-calculator.com</A>'
'<a class="whitelink" href="http://www.ascii-code.com/">ASCII-BIN-HEX-OCT Convert</a>'
'<a class="whitelink" href="https://www.iana.org/assignments/ieee-802-numbers/ieee-802-numbers.xhtml">IANA EtherType &amp; OUI #s</A>'
'<a class="whitelink" href="https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml">IANA ICMP Types &amp; Codes</A>'
'<a class="whitelink" href="https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml">IANA Internet Protocol #s</A>'
'<a class="whitelink" href="https://www.iana.org/assignments/ipv6-address-space/ipv6-address-space.xhtml">IANA IPv6 Address Space</A>'
'<a class="whitelink" href="https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt">IANA Transport Protocol #s</A>'
'<span class="yellowsans">Cisco Related</span>'
'<a class="whitelink" href="http://www.cisco.com/c/en/us/support/ios-nx-os-software/ios-software-release-15-6-2-t/model.html">Cisco IOS 15.6(2)T Cmd Refs</A>'
'<a class="whitelink" href="http://www.cisco.com/c/en/us/support/ios-nx-os-software/ios-software-release-15-6m-t/products-command-reference-list.html">IOS 15.6(2) Services Cmd Guides</A>' 
'<a class="whitelink" href="http://www.cisco.com/c/en/us/support/ios-nx-os-software/ios-software-release-15-6m-t/products-installation-and-configuration-guides-list.html">Cisco IOS 15.6(2)T Config Guides</A>'
'<a class="whitelink" href="http://www.cisco.com/c/en/us/support/ios-nx-os-software/ios-xe-3e/tsd-products-support-series-home.html">Cisco IOS XE 3.x Cmd Refs</a>'
'<a class="whitelink" href="http://www.cisco.com/c/en/us/support/ios-nx-os-software/ios-xr-software/tsd-products-support-series-home.html">Cisco IOS XR Cmd Refs</a>'
'<a class="whitelink" href="http://www.cisco.com/c/en/us/support/ios-nx-os-software/nx-os-software/tsd-products-support-series-home.html">Cisco IOS NX Cmd Refs</a>'
'<a class="whitelink" href="https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/mpls/command/mp-cr-book.html">Cisco IOS MPLS Cmd Ref</A>'
'<a class="whitelink" href="https://sites.google.com/site/amitsciscozone/home
'<a class="whitelink" href="https://market.alcatel-lucent.com/release/jsp/sso/login.jsp">Nokia Alcatel-Lucent Portal</A>' 
'<a class="whitelink" href="https://www.arista.com/en/support/product-documentation">Arista reference docs</A>' 
'<a class="whitelink" href="https://www.arista.com/en/um-eos/eos-command-line-interface">Arista EOS CLI Reference</A>'
'<a class="whitelink" href="https://www.extremenetworks.com/support/">Extreme Networks - support and docs</A>'
'<a class="whitelink" href="https://supportforums.adtran.com">ADTRAN support</A>'
'<span class="yellowsans">AS/ BGP Lookups</span>'
'<a class="whitelink" href="https://www.bgpmon.net/">BGPMon Dashboard</A>'
'<a class="whitelink" href="http://bgp.he.net/">Hurricane Electric BGP Tools</A>'
'<a class="whitelink" href="http://www.netconfigs.com/">netconfigs.com BGP Tools</A>'
'<a class="whitelink" href="http://www.as3257.net/lg/">GTT BGP Looking Glass</A>'
'<a class="whitelink" href="https://prefix.pch.net/">Packet Clearinghouse</A>'
'<a class="whitelink" href="https://www.peeringdb.com/advanced_search">PeeringDB Adv Search</A>'
'<a class="whitelink" href="http://cyclops.cs.ucla.edu/">Cyclops network audit tool</A>'
'<a class="whitelink" href="https://www.team-cymru.org/services.html">Team Cymru IP-to-ASN, etc</A>'
'<a class="whitelink" href="https://www.findip-address.com/">Findip-address.com Lookup</A>'
'<a class="whitelink" href="https://myip.ms/">myip.ms Host Info</a>'
'<a class="whitelink" href="http://trace.die.net/">die.net TraceRoute Explorer</a>'
'<a class="whitelink" href="http://www.traceroute.org/">Traceroute.org Jumppoints</a>' 
'<span class="yellowsans">Route Servers, etc</span>'
'<a class="whitelink" href="telnet://route-server.ip.att.net">telnet://route-server.ip.att.net</A>'
'<a class="whitelink" href="telnet://route-server.rogers.com">telnet://route-server.rogers.com</A>'
'<a class="whitelink" href="telnet://route-server.cerf.net">telnet://route-server.cerf.net</A>'
'<a class="whitelink" href="telnet://route-server.videotron.net">telnet://route-server.videotron.net</A>'
'<a class="whitelink" href="http://www.traceroute.org">Public route servers list</A>'
'<a class="whitelink" href="https://www.irr.net">Internet Routing Registry (IRR)</A>'
'<a class="whitelink" href="https://irrexplorer.nlnog.net">NL NOG IRR Explorer</A>'
'<a class="whitelink" href="https://nlnog.net/tools/">NL NOG tools</A>'